Open zeplin
metaxu-art/smart-contracts pull request #5
Opened 2021-01-26 21:00 UTC by Samson303

Changes: 

- Moved game logic out of token contract
- token contract inherits from OpenZeplin ERC20 and Ownable
- Moved all to Rinkeby (all contract details ex. address in readMe)

2021-01-27 10:20 UTC, diminator approved these changes
very clean

2021-01-27 10:20 UTC, diminator commented on contracts/MetaxuGameAdmin.sol
> +    mapping(bytes32 => uint256)easterEggToReward_;
style nit: spaces after `)`

2021-01-27 10:20 UTC, diminator commented on contracts/MetaxuGameAdmin.sol
> +        bytes32 hash = sha256(abi.encodePacked(str));
can also use `keccak`. is more secure (SHA3). but maybe costs more gas...

2021-01-27 10:20 UTC, diminator commented on contracts/MetaxuGameAdmin.sol
> +            if (eligableForAirDrop_[listOfRecepients[index]]) {
could be removed as you can always set `true` without check

2021-01-27 10:20 UTC, diminator commented on contracts/MetaxuGameAdmin.sol
> +    mapping (address => bool) recievedAirDrop_;
`receive`, not `recieve`

2021-01-27 10:23 UTC, diminator commented on contracts/MTX.sol
> +contract MTX is ERC20, Ownable {
for alternatives:
https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC20
I could see `Pausable` as a nice feature

2021-01-27 10:39 UTC, diminator requested changes

2021-01-27 10:39 UTC, diminator commented on contracts/MTX.sol
> +    function mint (address callingContract, address accountMintedTo, uint256 amount) public  {
there's also a ERC20 templates that have `Minter` roles. maybe need to investigate that

2021-01-27 10:39 UTC, diminator commented on contracts/MTX.sol
> +    function mint (address callingContract, address accountMintedTo, uint256 amount) public  {
https://docs.openzeppelin.com/contracts/3.x/api/presets#ERC20PresetMinterPauser

2021-01-27 10:39 UTC, diminator commented on contracts/MetaxuGameAdmin.sol
> +        require(!hasBeenRedeemed_[hashOfAttempt], 'easter egg has been redeemed');
this mean we'll only can use one secret each time and never reuse it.
If we want to reuse secrets we could do something like
```
easterEggToReward_[hashOfAttempt] = 0
```
at the end and remove `hasBeenRedeemed`

2021-01-27 21:42 UTC, Samson303 commented on contracts/MetaxuGameAdmin.sol
> +        require(!hasBeenRedeemed_[hashOfAttempt], 'easter egg has been redeemed');
has been removed and implemented a secretData struct which holds property of amountLeft that can be topped up

2021-01-27 21:43 UTC, Samson303 commented on contracts/MTX.sol
> +    function mint (address callingContract, address accountMintedTo, uint256 amount) public  {
implemented and minters will be msg.sender and game contract (added after uploading of contract)

2021-01-27 21:44 UTC, Samson303 commented on contracts/MTX.sol
> +contract MTX is ERC20, Ownable {
using openZeplin ERC20PresetMinterPauser

2021-01-27 21:44 UTC, Samson303 commented on contracts/MetaxuGameAdmin.sol
> +        bytes32 hash = sha256(abi.encodePacked(str));
changed to keccak256 on new commit

2021-01-27 21:45 UTC, Samson303 commented on contracts/MetaxuGameAdmin.sol
> +    mapping(bytes32 => uint256)easterEggToReward_;
changed on new commit

2021-01-28 11:09 UTC, diminator approved these changes

2021-01-28 11:19 UTC, diminator approved these changes

2021-01-28 11:20 UTC, merged